networks:
 default: 
  driver: bridge 
  name: roboshop
  #external: true #I created network already using docker network create roboshop 

services:
 mongodb: 
  image: siva3150/mongodb:v1 
  container_name: mongodb 
 catalogue:
  image: siva3150/catalogue:v1 
  container_name: catalogue 
  depends_on:
  - mongodb 
 redis: 
  image: redis:7.0 
  container_name: redis 
 user: 
  image: siva3150/user:v1 
  container_name: user 
  depends_on:
  - redis  
  - mongodb
 cart: 
  image: siva3150/cart:v1 
  container_name: cart 
  depends_on:
  - catalogue 
  - redis 
 mysql: 
  image: siva3150/mysql:v1 
  container_name: mysql 
 shipping: 
  image: siva3150/shipping:v1
  container_name: shipping 
  depends_on: 
  - mysql 
  - cart  
 rabbitmq: 
  image: rabbitmq:3 
  container_name: rabbitmq 
  environment: 
   RABBITMQ_DEFAULT_USER: roboshop 
   RABBITMQ_DEFAULT_PASS: roboshop123  
 payment:
  image: siva3150/payment:v1 
  container_name: payment 
  environment:
   CART_HOST: cart 
   CART_PORT: 8080
   USER_HOST: user 
   USER_PORT: 8080 
   AMQP_HOST: rabbitmq 
   AMQP_USER: roboshop 
   AMQP_PASS: roboshop123
  depends_on:
  - cart
  - user 
  - rabbitmq 